# Generated by Django 5.2.3 on 2025-06-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AidRequestManagement', '0001_initial'),
        ('ShelterDirectory', '0001_initial'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_aid_requests', to='UserManagement.citizen'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_request_emails', to='UserManagement.citizen'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='requester_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='UserManagement.citizen'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='shelter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='ShelterDirectory.shelter'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_aid_requests', to='UserManagement.authority'),
        ),
    ]
