# Generated by Django 5.2.3 on 2025-06-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelterDirectory', '0004_alter_shelter_code_alter_shelter_location'),
        ('UserManagement', '0003_alter_role_name'),
        ('VolunteerCoordination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='UserManagement.authority')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ShelterDirectory.shelter')),
                ('volunteers', models.ManyToManyField(related_name='tasks', to='UserManagement.volunteer')),
            ],
        ),
    ]
