# Generated by Django 5.2.3 on 2025-06-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolunteerCoordination', '0003_remove_volunteertask_volunteers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteertask',
            old_name='assigned_date',
            new_name='created_date',
        ),
    ]
