# Generated by Django 5.2.3 on 2025-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolunteerCoordination', '0004_rename_assigned_date_volunteertask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerassignments',
            name='volunteer',
            field=models.CharField(max_length=255),
        ),
    ]
