# Generated by Django 5.2.3 on 2025-06-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolunteerCoordination', '0005_alter_volunteerassignments_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteertask',
            old_name='description',
            new_name='skills',
        ),
    ]
