# Generated by Django 5.2.3 on 2025-06-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DisasterReporting', '0001_initial'),
        ('UserManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='reporter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_reports', to='UserManagement.citizen'),
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disaster_reports_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
