# Generated by Django 5.2.3 on 2025-06-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterReporting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
