# Generated by Django 5.2.3 on 2025-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(max_length=100)),
                ('gps_coordinates', models.CharField(help_text='Enter GPS coordinates in the format: latitude,longitude', max_length=100)),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', help_text='Select the severity level of the disaster', max_length=50)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
