# Generated by Django 5.2.3 on 2025-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('authorities', 'Authorities'), ('citizens', 'Citizens'), ('volunteers', 'Volunteer')], max_length=100, unique=True),
        ),
    ]
