# Generated by Django 5.2.3 on 2025-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_role_id_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('authorities', 'Authorities'), ('citizens', 'Citizens'), ('volunteers', 'Volunteers')], max_length=100, unique=True),
        ),
    ]
