# Generated by Django 5.2.3 on 2025-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidRequestManagement', '0003_alter_aidrequest_requester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
