# Generated by Django 5.2.3 on 2025-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidRequestManagement', '0004_alter_aidrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
