# Generated by Django 5.2.3 on 2025-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidRequestManagement', '0005_alter_aidrequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
