# Generated by Django 5.2.3 on 2025-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_role_name'),
        ('VolunteerCoordination', '0006_rename_description_volunteertask_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='UserManagement.volunteer'),
        ),
    ]
