# Generated by Django 5.2.3 on 2025-06-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShelterDirectory', '0001_initial'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters_created', to='UserManagement.authority'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelters_updated', to='UserManagement.authority'),
        ),
    ]
