# Generated by Django 5.2.3 on 2025-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelterDirectory', '0003_alter_shelter_code_alter_shelter_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='location',
            field=models.TextField(),
        ),
    ]
